<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'psr\\log\\abstractlogger' => '/AbstractLogger.php',
                'psr\\log\\invalidargumentexception' => '/InvalidArgumentException.php',
                'psr\\log\\loggerawareinterface' => '/LoggerAwareInterface.php',
                'psr\\log\\loggerawaretrait' => '/LoggerAwareTrait.php',
                'psr\\log\\loggerinterface' => '/LoggerInterface.php',
                'psr\\log\\loggertrait' => '/LoggerTrait.php',
                'psr\\log\\loglevel' => '/LogLevel.php',
                'psr\\log\\nulllogger' => '/NullLogger.php',
                'psr\\log\\test\\dummytest' => '/Test/LoggerInterfaceTest.php',
                'psr\\log\\test\\loggerinterfacetest' => '/Test/LoggerInterfaceTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
