<?php

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'symfony\\component\\finder\\comparator\\comparator' => '/Comparator/Comparator.php',
                'symfony\\component\\finder\\comparator\\datecomparator' => '/Comparator/DateComparator.php',
                'symfony\\component\\finder\\comparator\\numbercomparator' => '/Comparator/NumberComparator.php',
                'symfony\\component\\finder\\exception\\accessdeniedexception' => '/Exception/AccessDeniedException.php',
                'symfony\\component\\finder\\exception\\exceptioninterface' => '/Exception/ExceptionInterface.php',
                'symfony\\component\\finder\\finder' => '/Finder.php',
                'symfony\\component\\finder\\glob' => '/Glob.php',
                'symfony\\component\\finder\\iterator\\customfilteriterator' => '/Iterator/CustomFilterIterator.php',
                'symfony\\component\\finder\\iterator\\daterangefilteriterator' => '/Iterator/DateRangeFilterIterator.php',
                'symfony\\component\\finder\\iterator\\depthrangefilteriterator' => '/Iterator/DepthRangeFilterIterator.php',
                'symfony\\component\\finder\\iterator\\excludedirectoryfilteriterator' => '/Iterator/ExcludeDirectoryFilterIterator.php',
                'symfony\\component\\finder\\iterator\\filecontentfilteriterator' => '/Iterator/FilecontentFilterIterator.php',
                'symfony\\component\\finder\\iterator\\filenamefilteriterator' => '/Iterator/FilenameFilterIterator.php',
                'symfony\\component\\finder\\iterator\\filetypefilteriterator' => '/Iterator/FileTypeFilterIterator.php',
                'symfony\\component\\finder\\iterator\\filteriterator' => '/Iterator/FilterIterator.php',
                'symfony\\component\\finder\\iterator\\multiplepcrefilteriterator' => '/Iterator/MultiplePcreFilterIterator.php',
                'symfony\\component\\finder\\iterator\\pathfilteriterator' => '/Iterator/PathFilterIterator.php',
                'symfony\\component\\finder\\iterator\\recursivedirectoryiterator' => '/Iterator/RecursiveDirectoryIterator.php',
                'symfony\\component\\finder\\iterator\\sizerangefilteriterator' => '/Iterator/SizeRangeFilterIterator.php',
                'symfony\\component\\finder\\iterator\\sortableiterator' => '/Iterator/SortableIterator.php',
                'symfony\\component\\finder\\splfileinfo' => '/SplFileInfo.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn]) and file_exists(__DIR__ . $classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
