<?php

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'symfony\\component\\process\\exception\\exceptioninterface' => '/Exception/ExceptionInterface.php',
                'symfony\\component\\process\\exception\\invalidargumentexception' => '/Exception/InvalidArgumentException.php',
                'symfony\\component\\process\\exception\\logicexception' => '/Exception/LogicException.php',
                'symfony\\component\\process\\exception\\processfailedexception' => '/Exception/ProcessFailedException.php',
                'symfony\\component\\process\\exception\\processtimedoutexception' => '/Exception/ProcessTimedOutException.php',
                'symfony\\component\\process\\exception\\runtimeexception' => '/Exception/RuntimeException.php',
                'symfony\\component\\process\\executablefinder' => '/ExecutableFinder.php',
                'symfony\\component\\process\\inputstream' => '/InputStream.php',
                'symfony\\component\\process\\phpexecutablefinder' => '/PhpExecutableFinder.php',
                'symfony\\component\\process\\phpprocess' => '/PhpProcess.php',
                'symfony\\component\\process\\pipes\\abstractpipes' => '/Pipes/AbstractPipes.php',
                'symfony\\component\\process\\pipes\\pipesinterface' => '/Pipes/PipesInterface.php',
                'symfony\\component\\process\\pipes\\unixpipes' => '/Pipes/UnixPipes.php',
                'symfony\\component\\process\\pipes\\windowspipes' => '/Pipes/WindowsPipes.php',
                'symfony\\component\\process\\process' => '/Process.php',
                'symfony\\component\\process\\processbuilder' => '/ProcessBuilder.php',
                'symfony\\component\\process\\processutils' => '/ProcessUtils.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn]) and file_exists(__DIR__ . $classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
