#!/bin/sh

set -e

# Automatically added by dh_systemd_start/11.1.6ubuntu2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.6ubuntu2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'hibinit-agent.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'hibinit-agent.service' >/dev/null || true
		deb-systemd-helper unmask 'hibinit-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


case "$1" in
    remove)
        deb-systemd-invoke restart systemd-logind.service || true
        ;;
    purge)
        invoke-rc.d acpid restart > /dev/null || true
        deb-systemd-invoke restart systemd-logind.service || true
        # clean up dynamically added conffile if exists
        rm -f /etc/default/grub.d/99-set-swap.cfg
        update-grub2 || true
        swapoff /swap-hibinit > /dev/null 2>&1 || true
        rm -f /swap-hibinit
        ;;
    *)
        ;;
esac
