<?php

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'symfony\\component\\filesystem\\exception\\exceptioninterface' => '/Exception/ExceptionInterface.php',
                'symfony\\component\\filesystem\\exception\\filenotfoundexception' => '/Exception/FileNotFoundException.php',
                'symfony\\component\\filesystem\\exception\\ioexception' => '/Exception/IOException.php',
                'symfony\\component\\filesystem\\exception\\ioexceptioninterface' => '/Exception/IOExceptionInterface.php',
                'symfony\\component\\filesystem\\filesystem' => '/Filesystem.php',
                'symfony\\component\\filesystem\\lockhandler' => '/LockHandler.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn]) and file_exists(__DIR__ . $classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
