<?php
// require:
require_once 'Psr/Log/autoload.php';

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'symfony\\component\\debug\\bufferinglogger' => '/BufferingLogger.php',
                'symfony\\component\\debug\\debug' => '/Debug.php',
                'symfony\\component\\debug\\debugclassloader' => '/DebugClassLoader.php',
                'symfony\\component\\debug\\errorhandler' => '/ErrorHandler.php',
                'symfony\\component\\debug\\exception\\classnotfoundexception' => '/Exception/ClassNotFoundException.php',
                'symfony\\component\\debug\\exception\\contexterrorexception' => '/Exception/ContextErrorException.php',
                'symfony\\component\\debug\\exception\\fatalerrorexception' => '/Exception/FatalErrorException.php',
                'symfony\\component\\debug\\exception\\fatalthrowableerror' => '/Exception/FatalThrowableError.php',
                'symfony\\component\\debug\\exception\\flattenexception' => '/Exception/FlattenException.php',
                'symfony\\component\\debug\\exception\\outofmemoryexception' => '/Exception/OutOfMemoryException.php',
                'symfony\\component\\debug\\exception\\silencederrorcontext' => '/Exception/SilencedErrorContext.php',
                'symfony\\component\\debug\\exception\\undefinedfunctionexception' => '/Exception/UndefinedFunctionException.php',
                'symfony\\component\\debug\\exception\\undefinedmethodexception' => '/Exception/UndefinedMethodException.php',
                'symfony\\component\\debug\\exceptionhandler' => '/ExceptionHandler.php',
                'symfony\\component\\debug\\fatalerrorhandler\\classnotfoundfatalerrorhandler' => '/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php',
                'symfony\\component\\debug\\fatalerrorhandler\\fatalerrorhandlerinterface' => '/FatalErrorHandler/FatalErrorHandlerInterface.php',
                'symfony\\component\\debug\\fatalerrorhandler\\undefinedfunctionfatalerrorhandler' => '/FatalErrorHandler/UndefinedFunctionFatalErrorHandler.php',
                'symfony\\component\\debug\\fatalerrorhandler\\undefinedmethodfatalerrorhandler' => '/FatalErrorHandler/UndefinedMethodFatalErrorHandler.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn]) and file_exists(__DIR__ . $classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
