<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'jsonschema\\constraints\\baseconstraint' => '/Constraints/BaseConstraint.php',
                'jsonschema\\constraints\\collectionconstraint' => '/Constraints/CollectionConstraint.php',
                'jsonschema\\constraints\\constraint' => '/Constraints/Constraint.php',
                'jsonschema\\constraints\\constraintinterface' => '/Constraints/ConstraintInterface.php',
                'jsonschema\\constraints\\enumconstraint' => '/Constraints/EnumConstraint.php',
                'jsonschema\\constraints\\factory' => '/Constraints/Factory.php',
                'jsonschema\\constraints\\formatconstraint' => '/Constraints/FormatConstraint.php',
                'jsonschema\\constraints\\numberconstraint' => '/Constraints/NumberConstraint.php',
                'jsonschema\\constraints\\objectconstraint' => '/Constraints/ObjectConstraint.php',
                'jsonschema\\constraints\\schemaconstraint' => '/Constraints/SchemaConstraint.php',
                'jsonschema\\constraints\\stringconstraint' => '/Constraints/StringConstraint.php',
                'jsonschema\\constraints\\typecheck\\loosetypecheck' => '/Constraints/TypeCheck/LooseTypeCheck.php',
                'jsonschema\\constraints\\typecheck\\stricttypecheck' => '/Constraints/TypeCheck/StrictTypeCheck.php',
                'jsonschema\\constraints\\typecheck\\typecheckinterface' => '/Constraints/TypeCheck/TypeCheckInterface.php',
                'jsonschema\\constraints\\typeconstraint' => '/Constraints/TypeConstraint.php',
                'jsonschema\\constraints\\undefinedconstraint' => '/Constraints/UndefinedConstraint.php',
                'jsonschema\\entity\\jsonpointer' => '/Entity/JsonPointer.php',
                'jsonschema\\exception\\exceptioninterface' => '/Exception/ExceptionInterface.php',
                'jsonschema\\exception\\invalidargumentexception' => '/Exception/InvalidArgumentException.php',
                'jsonschema\\exception\\invalidconfigexception' => '/Exception/InvalidConfigException.php',
                'jsonschema\\exception\\invalidschemaexception' => '/Exception/InvalidSchemaException.php',
                'jsonschema\\exception\\invalidschemamediatypeexception' => '/Exception/InvalidSchemaMediaTypeException.php',
                'jsonschema\\exception\\invalidsourceuriexception' => '/Exception/InvalidSourceUriException.php',
                'jsonschema\\exception\\jsondecodingexception' => '/Exception/JsonDecodingException.php',
                'jsonschema\\exception\\resourcenotfoundexception' => '/Exception/ResourceNotFoundException.php',
                'jsonschema\\exception\\runtimeexception' => '/Exception/RuntimeException.php',
                'jsonschema\\exception\\unresolvablejsonpointerexception' => '/Exception/UnresolvableJsonPointerException.php',
                'jsonschema\\exception\\uriresolverexception' => '/Exception/UriResolverException.php',
                'jsonschema\\exception\\validationexception' => '/Exception/ValidationException.php',
                'jsonschema\\iterator\\objectiterator' => '/Iterator/ObjectIterator.php',
                'jsonschema\\rfc3339' => '/Rfc3339.php',
                'jsonschema\\schemastorage' => '/SchemaStorage.php',
                'jsonschema\\schemastorageinterface' => '/SchemaStorageInterface.php',
                'jsonschema\\uri\\retrievers\\abstractretriever' => '/Uri/Retrievers/AbstractRetriever.php',
                'jsonschema\\uri\\retrievers\\curl' => '/Uri/Retrievers/Curl.php',
                'jsonschema\\uri\\retrievers\\filegetcontents' => '/Uri/Retrievers/FileGetContents.php',
                'jsonschema\\uri\\retrievers\\predefinedarray' => '/Uri/Retrievers/PredefinedArray.php',
                'jsonschema\\uri\\retrievers\\uriretrieverinterface' => '/Uri/Retrievers/UriRetrieverInterface.php',
                'jsonschema\\uri\\uriresolver' => '/Uri/UriResolver.php',
                'jsonschema\\uri\\uriretriever' => '/Uri/UriRetriever.php',
                'jsonschema\\uriresolverinterface' => '/UriResolverInterface.php',
                'jsonschema\\uriretrieverinterface' => '/UriRetrieverInterface.php',
                'jsonschema\\validator' => '/Validator.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
